### ISSUE TITLE
Granary Smart Feeder and Integration

### ISSUE THREAD

**Issue by trentsmart** [jjjonesjr33/petlibro#2]
I have version 1.0.5 and I see that you said the Granary Smart Feeder is now working with the integration. I have that feeder and it's still not showing up as a device in home assistant, I also saw theres a newer version 1.0.6. When I first downloaded the integration it said it was downloading 1.0.6 but I ended up with 1.0.5. Just curious if I need to do anything else to get my feeder to show up. Thank you for this integration by the way, I've been waiting for this.

**Comment by jjjonesjr33** [comment]
I think that was an issue on my side with the [manifest.json](https://github.com/jjjonesjr33/petlibro/commit/aa821b3af1325550a68f5a0a63ea882691ffa7fe) not being updated when I did that latest push. It's been changed/updated. When I push the next update it will reflect the change in Home Assistant.

Thanks for letting me know!

**Comment by jjjonesjr33** [comment]
Sorry didn't mean to close the issue. So your saying the `Granary Smart Feeder` isn't working for you?

Can you tell me the exact model you have? And are you able to see/pull any info from the debug log in Home Assistant?

You can see the logs by adding this into your `configuration.yaml`

```yaml
logger:
  default: warning  # Default log level for all components
  logs:
    custom_components.petlibro: debug    # Enable debug logging for your component
```

Please let me know what you find out.
