### ISSUE TITLE
[Device]: PLAF103 - PETLIBRO 5L Futterautomat 5G/2.4G WiFi Intelligenter Katzenfutter Automat

### ISSUE THREAD

**Issue by saschanaumann** [jjjonesjr33/petlibro#85]
### Device model name

Granary WiFi Futterautomat

### Device model number

PLAF103

### Device type

Feeder

### What state, statistic or control do you want to be reported in the integration ?

Es wäre super wenn dise Geräte auch dabei wären.

### Available to help integrate the new device

- [x] I agree to help with the integration of the new device by providing the necessary information that will be requested

**Comment by jjjonesjr33** [comment]
On the `PLAF103` version, only the `Granary Smart Feeder (PLAF103) | Version 2` is supported. Version 1 is not supported as it does not work with the new Petlibro app.

Can you confirm what device model you have?

**Comment by saschanaumann** [comment]
The device is 6 months old and works perfectly via the app.
I took a picture of the device for you.
In the original app, everything is fine and works great.

![Image](https://github.com/user-attachments/assets/8da2642f-35cd-4494-9996-da2a0840723b)

**Comment by jjjonesjr33** [comment]
@saschanaumann interesting, can you turn on troubleshoot mode in Home Assistant and provide the logs when you log in to the petlibro component?


To troubleshoot your Home Assistant instance, you can add the following configuration to your configuration.yaml file
```
logger:
  default: warning  # Default log level for all components
  logs:
    custom_components.petlibro: debug    # Enable debug logging for your component
```
